### PR TITLE
Add support for ERC-1271 signature verification

### PR DESCRIPTION
**Pull request by ksmithbaylor**

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>1</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>2</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by andrew-reder-cb — APPROVED** [review]
LGTM

**Comment by Tkelley325** [comment]
[@****]()

**Review by Sturgeontara06 — COMMENTED** [review]
No clue

**Comment by Irasone** [comment]
Pull

**Review by WOweeWee4real — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for WOweeWee4real @ 2024-12-29 04:42:47 UTC
User must have write permissions to review

**Review by WOweeWee4real — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for WOweeWee4real @ 2024-12-29 05:24:41 UTC
User must have write permissions to review

**Comment by samueldreadfulwater3-hash** [comment]
To

**Review by Uthen242 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Uthen242 @ 2026-04-12 10:25:38 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by Uthen242 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Uthen242 @ 2026-04-12 10:26:01 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by Uthen242 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Uthen242 @ 2026-04-12 10:26:32 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by Uthen242 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Uthen242 @ 2026-04-12 10:28:11 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by Uthen242 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Uthen242 @ 2026-04-25 06:51:53 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Review by Uthen242 — APPROVED** [review]

**Pull request merged**
